# Generated by Django 5.2.16 on 2026-07-20 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_friend_code_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='blocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_friendships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserAppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_request_privacy', models.CharField(choices=[('everyone', 'Everyone'), ('friends_of_friends', 'Friends of Friends'), ('nobody', 'Nobody')], default='everyone', max_length=30)),
                ('group_invite_privacy', models.CharField(choices=[('friends_only', 'Friends Only'), ('nobody', 'Nobody')], default='friends_only', max_length=30)),
                ('notification_friend_requests', models.BooleanField(default=True)),
                ('notification_group_invites', models.BooleanField(default=True)),
                ('notification_pick_session_invites', models.BooleanField(default=True)),
                ('notification_group_vote_started', models.BooleanField(default=True)),
                ('notification_voting_reminders', models.BooleanField(default=True)),
                ('notification_session_results', models.BooleanField(default=True)),
                ('notification_general', models.BooleanField(default=True)),
                ('theme', models.CharField(choices=[('system', 'System'), ('light', 'Light'), ('dark', 'Dark')], default='system', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user__email',),
            },
        ),
    ]
