# Generated by Django 5.2.16 on 2026-07-24 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_socialidentity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialidentity',
            name='provider',
            field=models.CharField(choices=[('apple', 'Apple'), ('google', 'Google'), ('facebook', 'Facebook')], max_length=20),
        ),
    ]
