# Generated by Django 5.2.16 on 2026-08-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_pushdevicetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_product_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_provider',
            field=models.CharField(blank=True, choices=[('apple', 'Apple App Store'), ('google', 'Google Play'), ('manual', 'Manual / Internal')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_status',
            field=models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('grace_period', 'Grace Period'), ('canceled', 'Canceled'), ('expired', 'Expired')], default='inactive', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_tier',
            field=models.CharField(choices=[('free', 'Free'), ('plus', "Pick Sum'N Plus")], default='free', max_length=20),
        ),
    ]
