# Generated by Django 5.2.16 on 2026-08-20 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_subscription_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userappsettings',
            name='matches_view_mode',
            field=models.CharField(choices=[('detailed', 'Detailed'), ('compact', 'Compact')], default='detailed', max_length=20),
        ),
    ]
