# Generated by Django 5.2.16 on 2026-08-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userappsettings_matches_view_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_environment',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_original_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_transaction_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
