# Generated by Django 5.2.16 on 2026-08-21 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_subscription_environment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_last_notification_signed_at',
            field=models.BigIntegerField(default=0),
        ),
    ]
