# Generated by Django 5.2.16 on 2026-07-14 05:31

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dining_groups', '0001_initial'),
        ('preferences', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('waiting', 'Waiting for Participants'), ('ready', 'Ready'), ('matching', 'Finding Matches'), ('voting', 'Voting'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('decision_mode', models.CharField(choices=[('ranked', 'Ranked Results'), ('pick_for_us', 'Pick For Us'), ('group_vote', 'Group Vote'), ('roulette', 'Restaurant Roulette'), ('swipe', 'Swipe Mode'), ('elimination', 'Elimination Mode')], default='ranked', max_length=30)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_label', models.CharField(blank=True, max_length=255)),
                ('search_radius_miles', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('price_min', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('price_max', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('open_now', models.BooleanField(default=True)),
                ('include_delivery', models.BooleanField(default=False)),
                ('include_drive_through', models.BooleanField(default=False)),
                ('something_new', models.BooleanField(default=False)),
                ('exclude_recent_days', models.PositiveSmallIntegerField(default=7)),
                ('vetoes_per_participant', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('selected_restaurant_external_id', models.CharField(blank=True, help_text='Temporary external restaurant ID until the restaurant domain is added.', max_length=255)),
                ('selected_restaurant_name', models.CharField(blank=True, max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_pick_sessions', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick_sessions', to='dining_groups.dininggroup')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PickSessionCuisineFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_session_filters', to='preferences.cuisine')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuisine_filters', to='pick_sessions.picksession')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('session', 'cuisine'), name='unique_pick_session_cuisine_filter')],
            },
        ),
        migrations.CreateModel(
            name='PickSessionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('joined', 'Joined'), ('ready', 'Ready'), ('declined', 'Declined'), ('left', 'Left')], default='invited', max_length=20)),
                ('is_host', models.BooleanField(default=False)),
                ('vetoes_used', models.PositiveSmallIntegerField(default=0)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='pick_sessions.picksession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_session_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-is_host', 'created_at'),
                'constraints': [models.UniqueConstraint(fields=('session', 'user'), name='unique_pick_session_participant')],
            },
        ),
    ]
