# Generated by Django 5.2.16 on 2026-07-16 05:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pick_sessions', '0002_picksessionparticipant_is_current_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickSessionRestaurantOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('rank', models.PositiveSmallIntegerField()),
                ('match_score', models.PositiveSmallIntegerField(default=0)),
                ('restaurant_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_options', to='pick_sessions.picksession')),
            ],
            options={
                'ordering': ('rank', 'name'),
            },
        ),
        migrations.CreateModel(
            name='PickSessionVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='pick_sessions.picksessionrestaurantoption')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='pick_sessions.picksessionparticipant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='pick_sessions.picksession')),
            ],
        ),
        migrations.AddConstraint(
            model_name='picksessionrestaurantoption',
            constraint=models.UniqueConstraint(fields=('session', 'external_id'), name='unique_group_vote_option_external_id'),
        ),
        migrations.AddConstraint(
            model_name='picksessionrestaurantoption',
            constraint=models.UniqueConstraint(fields=('session', 'rank'), name='unique_group_vote_option_rank'),
        ),
        migrations.AddConstraint(
            model_name='picksessionvote',
            constraint=models.UniqueConstraint(fields=('session', 'participant'), name='one_group_vote_per_participant'),
        ),
    ]
