# Generated by Django 5.2.16 on 2026-07-16 08:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pick_sessions', '0003_picksessionrestaurantoption_picksessionvote_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickSessionNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('group_vote_invite', 'Group Vote Invitation'), ('group_vote_completed', 'Group Vote Completed')], max_length=40)),
                ('title', models.CharField(max_length=120)),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='pick_sessions.picksession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_session_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('user', 'session', 'kind'), name='unique_pick_session_notification')],
            },
        ),
    ]
