# Generated for Pick Sum'N official menu intelligence

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pick_sessions",
            "0004_picksessionnotification",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RestaurantDietaryProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_place_id",
                    models.CharField(
                        max_length=255,
                    ),
                ),
                (
                    "restaurant_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                    ),
                ),
                (
                    "dietary_slug",
                    models.SlugField(
                        max_length=120,
                    ),
                ),
                (
                    "confidence_score",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0
                            ),
                            django.core.validators.MaxValueValidator(
                                100
                            ),
                        ],
                    ),
                ),
                (
                    "dedicated_facility",
                    models.BooleanField(
                        default=False,
                    ),
                ),
                (
                    "official_menu_found",
                    models.BooleanField(
                        default=False,
                    ),
                ),
                (
                    "official_source_url",
                    models.URLField(
                        blank=True,
                        max_length=1000,
                    ),
                ),
                (
                    "menu_items",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text=(
                            "Short menu labels or item names found on "
                            "the restaurant's official page."
                        ),
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                "found",
                                "Evidence Found",
                            ),
                            (
                                "not_found",
                                "No Evidence Found",
                            ),
                            (
                                "unavailable",
                                "Source Unavailable",
                            ),
                            (
                                "error",
                                "Analysis Error",
                            ),
                        ],
                        default="not_found",
                        max_length=20,
                    ),
                ),
                (
                    "last_checked_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "last_error",
                    models.CharField(
                        blank=True,
                        max_length=500,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                    ),
                ),
            ],
            options={
                "ordering": (
                    "-confidence_score",
                    "restaurant_name",
                    "dietary_slug",
                ),
            },
        ),
        migrations.CreateModel(
            name="RestaurantDietaryEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            (
                                "official_menu",
                                "Official Menu",
                            ),
                            (
                                "official_site",
                                "Official Website",
                            ),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "claim_type",
                    models.CharField(
                        max_length=60,
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        max_length=500,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        max_length=1000,
                    ),
                ),
                (
                    "confidence",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0
                            ),
                            django.core.validators.MaxValueValidator(
                                100
                            ),
                        ],
                    ),
                ),
                (
                    "observed_at",
                    models.DateTimeField(),
                ),
                (
                    "expires_at",
                    models.DateTimeField(),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=(
                            django.db.models.deletion.CASCADE
                        ),
                        related_name="evidence",
                        to=(
                            "pick_sessions."
                            "restaurantdietaryprofile"
                        ),
                    ),
                ),
            ],
            options={
                "ordering": (
                    "-confidence",
                    "-observed_at",
                ),
            },
        ),
        migrations.AddConstraint(
            model_name=(
                "restaurantdietaryprofile"
            ),
            constraint=models.UniqueConstraint(
                fields=(
                    "external_place_id",
                    "dietary_slug",
                ),
                name=(
                    "unique_restaurant_dietary_profile"
                ),
            ),
        ),
        migrations.AddIndex(
            model_name=(
                "restaurantdietaryprofile"
            ),
            index=models.Index(
                fields=(
                    "external_place_id",
                    "dietary_slug",
                ),
                name="pick_diet_place_slug_idx",
            ),
        ),
        migrations.AddIndex(
            model_name=(
                "restaurantdietaryprofile"
            ),
            index=models.Index(
                fields=("expires_at",),
                name="pick_diet_expires_idx",
            ),
        ),
        migrations.AddIndex(
            model_name=(
                "restaurantdietaryevidence"
            ),
            index=models.Index(
                fields=(
                    "profile",
                    "claim_type",
                ),
                name="pick_diet_claim_idx",
            ),
        ),
    ]
