# Generated for Pick Sum'N dietary community reports

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pick_sessions",
            "0005_restaurant_dietary_evidence",
        ),
        migrations.swappable_dependency(
            settings.AUTH_USER_MODEL
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RestaurantDietaryReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "external_place_id",
                    models.CharField(
                        max_length=255,
                    ),
                ),
                (
                    "restaurant_name",
                    models.CharField(
                        max_length=255,
                    ),
                ),
                (
                    "dietary_slug",
                    models.SlugField(
                        max_length=120,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            (
                                "accommodated",
                                "Successfully Accommodated",
                            ),
                            (
                                "partially_accommodated",
                                "Partially Accommodated",
                            ),
                            (
                                "not_accommodated",
                                "Could Not Accommodate",
                            ),
                            (
                                "reaction",
                                "Reaction After Eating",
                            ),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "items_clearly_labeled",
                    models.BooleanField(
                        default=False,
                    ),
                ),
                (
                    "staff_understood",
                    models.BooleanField(
                        default=False,
                    ),
                ),
                (
                    "dedicated_fryer",
                    models.BooleanField(
                        default=False,
                    ),
                ),
                (
                    "separate_preparation_area",
                    models.BooleanField(
                        default=False,
                    ),
                ),
                (
                    "gloves_changed",
                    models.BooleanField(
                        default=False,
                    ),
                ),
                (
                    "cross_contact_concern",
                    models.BooleanField(
                        default=False,
                    ),
                ),
                (
                    "restaurant_could_not_accommodate",
                    models.BooleanField(
                        default=False,
                    ),
                ),
                (
                    "reaction_after_eating",
                    models.BooleanField(
                        default=False,
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True,
                        max_length=500,
                    ),
                ),
                (
                    "visited_at",
                    models.DateField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "moderation_status",
                    models.CharField(
                        choices=[
                            (
                                "visible",
                                "Visible",
                            ),
                            (
                                "hidden",
                                "Hidden",
                            ),
                            (
                                "flagged",
                                "Flagged",
                            ),
                        ],
                        default="visible",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=(
                            django.db.models.deletion.CASCADE
                        ),
                        related_name=(
                            "restaurant_dietary_reports"
                        ),
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": (
                    "-updated_at",
                ),
            },
        ),
        migrations.AddConstraint(
            model_name=(
                "restaurantdietaryreport"
            ),
            constraint=models.UniqueConstraint(
                fields=(
                    "user",
                    "external_place_id",
                    "dietary_slug",
                ),
                name=(
                    "unique_user_restaurant_dietary_report"
                ),
            ),
        ),
        migrations.AddIndex(
            model_name=(
                "restaurantdietaryreport"
            ),
            index=models.Index(
                fields=(
                    "external_place_id",
                    "dietary_slug",
                    "moderation_status",
                ),
                name="pick_report_place_slug_idx",
            ),
        ),
    ]
