# Generated by Django 5.2.16 on 2026-07-19 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pick_sessions', '0006_restaurant_dietary_report'),
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickSessionDiningStyleFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dining_style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_session_filters', to='preferences.diningstyle')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dining_style_filters', to='pick_sessions.picksession')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('session', 'dining_style'), name='unique_pick_session_dining_style_filter')],
            },
        ),
    ]
