# Generated by Django 5.2.16 on 2026-07-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pick_sessions', '0007_picksessiondiningstylefilter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picksessionnotification',
            name='kind',
            field=models.CharField(choices=[('group_vote_invite', 'Group Vote Invitation'), ('group_vote_started', 'Group Vote Started'), ('group_vote_completed', 'Group Vote Completed')], max_length=40),
        ),
    ]
