# Generated by Django 5.2.16 on 2026-07-21 02:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pick_sessions', '0008_alter_picksessionnotification_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='picksession',
            name='selected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='picksession',
            name='selected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_selections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='picksession',
            name='selected_restaurant_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='picksession',
            name='selection_method',
            field=models.CharField(blank=True, choices=[('ranked_manual', 'Ranked Results - Manual Selection'), ('surprise_me', 'Surprise Me'), ('group_vote', 'Group Vote'), ('roulette', 'Restaurant Roulette'), ('swipe', 'Swipe Mode'), ('elimination', 'Elimination Mode')], max_length=30),
        ),
        migrations.AlterField(
            model_name='picksessionnotification',
            name='kind',
            field=models.CharField(choices=[('group_vote_invite', 'Group Vote Invitation'), ('group_vote_started', 'Group Vote Started'), ('group_vote_completed', 'Group Vote Completed'), ('restaurant_selected', 'Restaurant Selected')], max_length=40),
        ),
        migrations.CreateModel(
            name='PickSessionAnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('search_started', 'Search Started'), ('restaurant_impression', 'Restaurant Impression'), ('restaurant_detail_viewed', 'Restaurant Detail Viewed'), ('restaurant_selected', 'Restaurant Selected'), ('vote_cast', 'Vote Cast'), ('session_completed', 'Session Completed')], max_length=40)),
                ('restaurant_external_id', models.CharField(blank=True, max_length=255)),
                ('restaurant_name', models.CharField(blank=True, max_length=255)),
                ('event_data', models.JSONField(blank=True, default=dict)),
                ('dedupe_key', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to='pick_sessions.picksession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick_session_analytics_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='pick_sessio_event_t_ad3cef_idx'), models.Index(fields=['restaurant_external_id', 'created_at'], name='pick_sessio_restaur_2489e7_idx')],
            },
        ),
    ]
