# Generated by Django 5.2.16 on 2026-07-23 01:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pick_sessions', '0009_picksession_selected_at_picksession_selected_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='picksessionnotification',
            name='unique_pick_session_notification',
        ),
        migrations.AddField(
            model_name='picksessionnotification',
            name='dietary_slug',
            field=models.SlugField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='picksessionparticipant',
            name='visit_feedback',
            field=models.CharField(blank=True, choices=[('good_pick', 'Good Pick'), ('not_for_me', 'Not For Me'), ('didnt_go', "Didn't Go")], max_length=20),
        ),
        migrations.AddField(
            model_name='picksessionparticipant',
            name='visit_feedback_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='picksessionanalyticsevent',
            name='event_type',
            field=models.CharField(choices=[('search_started', 'Search Started'), ('restaurant_impression', 'Restaurant Impression'), ('restaurant_detail_viewed', 'Restaurant Detail Viewed'), ('restaurant_selected', 'Restaurant Selected'), ('vote_cast', 'Vote Cast'), ('session_completed', 'Session Completed'), ('restaurant_feedback', 'Restaurant Feedback'), ('confirmed_visit', 'Confirmed Visit')], max_length=40),
        ),
        migrations.AlterField(
            model_name='picksessionnotification',
            name='kind',
            field=models.CharField(choices=[('group_vote_invite', 'Group Vote Invitation'), ('group_vote_started', 'Group Vote Started'), ('group_vote_completed', 'Group Vote Completed'), ('restaurant_selected', 'Restaurant Selected'), ('dietary_feedback', 'Dietary Experience Feedback')], max_length=40),
        ),
        migrations.AddConstraint(
            model_name='picksessionnotification',
            constraint=models.UniqueConstraint(fields=('user', 'session', 'kind', 'dietary_slug'), name='unique_pick_session_notification'),
        ),
    ]
