# Generated by Django 5.2.16 on 2026-08-20 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pick_sessions', '0010_remove_picksessionnotification_unique_pick_session_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='picksession',
            name='gluten_free_filter_enabled',
            field=models.BooleanField(default=True, help_text='Whether gluten-free dietary matching should be applied for this session when selected participants have it set.'),
        ),
    ]
