# Generated by Django 5.2.16 on 2026-08-21 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pick_sessions', '0011_picksession_gluten_free_filter_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='picksession',
            name='match_variety',
            field=models.CharField(choices=[('balanced', 'Balanced Mix'), ('best', 'Best Matches')], default='balanced', help_text='Controls whether ranked results stay in pure score order or use a quality-preserving cuisine mix.', max_length=20),
        ),
    ]
