# Generated by Django 5.2.16 on 2026-07-15 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text='Google Places restaurant ID.', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('formatted_address', models.CharField(blank=True, max_length=500)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True)),
                ('primary_type', models.CharField(blank=True, max_length=120)),
                ('primary_type_display_name', models.CharField(blank=True, max_length=150)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('user_rating_count', models.PositiveIntegerField(default=0)),
                ('price_level', models.CharField(blank=True, max_length=80)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('website_uri', models.URLField(blank=True, max_length=1000)),
                ('google_maps_uri', models.URLField(blank=True, max_length=1000)),
                ('menu_uri', models.URLField(blank=True, max_length=1000)),
                ('photo_url', models.URLField(blank=True, max_length=2000)),
                ('delivery', models.BooleanField(blank=True, null=True)),
                ('dine_in', models.BooleanField(blank=True, null=True)),
                ('takeout', models.BooleanField(blank=True, null=True)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_restaurants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-saved_at',),
                'indexes': [models.Index(fields=['user', '-saved_at'], name='saved_rest_user_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'external_id'), name='unique_saved_restaurant_per_user')],
            },
        ),
    ]
