# Generated by Django 5.2.16 on 2026-07-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining_groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dininggroup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='groups/images/'),
        ),
    ]
