# Generated by Django 5.2.16 on 2026-07-14 02:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='DietaryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='DiningStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='FoodDislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='UserCuisinePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(choices=[(-2, 'Never'), (-1, 'Dislike'), (0, 'Neutral'), (1, 'Like'), (2, 'Love')], default=0)),
                ('rank', models.PositiveSmallIntegerField(blank=True, help_text='Optional top-five ranking.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='preferences.cuisine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuisine_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-level', 'rank', 'cuisine__name'),
                'constraints': [models.UniqueConstraint(fields=('user', 'cuisine'), name='unique_user_cuisine_preference')],
            },
        ),
        migrations.CreateModel(
            name='UserDietaryPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=False, help_text='Required preferences may disqualify restaurants that cannot accommodate them.')),
                ('dietary_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='preferences.dietarytag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dietary_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-is_required', 'dietary_tag__name'),
                'constraints': [models.UniqueConstraint(fields=('user', 'dietary_tag'), name='unique_user_dietary_preference')],
            },
        ),
        migrations.CreateModel(
            name='UserDiningStylePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(choices=[(-2, 'Never'), (-1, 'Dislike'), (0, 'Neutral'), (1, 'Like'), (2, 'Love')], default=0)),
                ('dining_style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='preferences.diningstyle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dining_style_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-level', 'dining_style__name'),
                'constraints': [models.UniqueConstraint(fields=('user', 'dining_style'), name='unique_user_dining_style_preference')],
            },
        ),
        migrations.CreateModel(
            name='UserFoodDislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_absolute', models.BooleanField(default=False, help_text='Absolute dislikes should strongly penalize or exclude unsuitable matches.')),
                ('food_dislike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='preferences.fooddislike')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_dislikes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-is_absolute', 'food_dislike__name'),
                'constraints': [models.UniqueConstraint(fields=('user', 'food_dislike'), name='unique_user_food_dislike')],
            },
        ),
    ]
