# Generated by Django 5.2.16 on 2026-07-14 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=280)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('default_search_radius_miles', models.PositiveSmallIntegerField(default=10)),
                ('default_price_min', models.PositiveSmallIntegerField(default=1)),
                ('default_price_max', models.PositiveSmallIntegerField(default=3)),
                ('exclude_recent_days', models.PositiveSmallIntegerField(default=7, help_text='Avoid restaurants visited within this many days.')),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user__email',),
            },
        ),
    ]
