# Generated by Django 5.2.16 on 2026-07-14 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dietary_section_completed',
            field=models.BooleanField(default=False, help_text='The user has reviewed the dietary section, including confirming that none apply.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='dislikes_section_completed',
            field=models.BooleanField(default=False, help_text='The user has reviewed the dislikes section, including confirming that none apply.'),
        ),
    ]
