# Generated by Django 5.2.16 on 2026-07-22 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_default_location_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_completion_card_dismissed',
            field=models.BooleanField(default=False),
        ),
    ]
